apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rbacsyncconfigs.rbacsync.getcruise.com
spec:
  group: rbacsync.getcruise.com
  names:
    kind: RBACSyncConfig
    plural: rbacsyncconfigs
    singular: rbacsyncconfig
    shortNames:
      - rsc
  scope: Namespaced
  versions:
    - name: v1alpha
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
  # TODO(sday): Create open API spec that validates all configs are RoleBindings
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterrbacsyncconfigs.rbacsync.getcruise.com
spec:
  group: rbacsync.getcruise.com
  names:
    kind: ClusterRBACSyncConfig
    plural: clusterrbacsyncconfigs
    singular: clusterrbacsyncconfig
    shortNames:
      - crsc
  scope: Cluster
  versions:
    - name: v1alpha
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
  # TODO(sday): Create open API spec that validates all configs are ClusterRoleBindings
